apiVersion: v1
kind: Service
metadata:
  name: mi-aplicacion-backend-service
spec:
  selector:
    app: mi-aplicacion-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
